// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	service "github.com/fishus/go-advanced-gophermart/internal/service"
)

// Servicer is an autogenerated mock type for the Servicer type
type Servicer struct {
	mock.Mock
}

type Servicer_Expecter struct {
	mock *mock.Mock
}

func (_m *Servicer) EXPECT() *Servicer_Expecter {
	return &Servicer_Expecter{mock: &_m.Mock}
}

// Order provides a mock function with given fields:
func (_m *Servicer) Order() service.Orderer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Order")
	}

	var r0 service.Orderer
	if rf, ok := ret.Get(0).(func() service.Orderer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Orderer)
		}
	}

	return r0
}

// Servicer_Order_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Order'
type Servicer_Order_Call struct {
	*mock.Call
}

// Order is a helper method to define mock.On call
func (_e *Servicer_Expecter) Order() *Servicer_Order_Call {
	return &Servicer_Order_Call{Call: _e.mock.On("Order")}
}

func (_c *Servicer_Order_Call) Run(run func()) *Servicer_Order_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Servicer_Order_Call) Return(_a0 service.Orderer) *Servicer_Order_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Servicer_Order_Call) RunAndReturn(run func() service.Orderer) *Servicer_Order_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with given fields:
func (_m *Servicer) User() service.Userer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 service.Userer
	if rf, ok := ret.Get(0).(func() service.Userer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Userer)
		}
	}

	return r0
}

// Servicer_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type Servicer_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *Servicer_Expecter) User() *Servicer_User_Call {
	return &Servicer_User_Call{Call: _e.mock.On("User")}
}

func (_c *Servicer_User_Call) Run(run func()) *Servicer_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Servicer_User_Call) Return(_a0 service.Userer) *Servicer_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Servicer_User_Call) RunAndReturn(run func() service.Userer) *Servicer_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewServicer creates a new instance of Servicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Servicer {
	mock := &Servicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
