// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

type User_Expecter struct {
	mock *mock.Mock
}

func (_m *User) EXPECT() *User_Expecter {
	return &User_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *User) Login(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// User_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type User_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *User_Expecter) Login(_a0 interface{}, _a1 interface{}) *User_Login_Call {
	return &User_Login_Call{Call: _e.mock.On("Login", _a0, _a1)}
}

func (_c *User_Login_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *User_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *User_Login_Call) Return() *User_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *User_Login_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *User_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *User) Register(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// User_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type User_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *User_Expecter) Register(_a0 interface{}, _a1 interface{}) *User_Register_Call {
	return &User_Register_Call{Call: _e.mock.On("Register", _a0, _a1)}
}

func (_c *User_Register_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *User_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *User_Register_Call) Return() *User_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *User_Register_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *User_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
