// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fishus/go-advanced-gophermart/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// LoyaltyBalancer is an autogenerated mock type for the LoyaltyBalancer type
type LoyaltyBalancer struct {
	mock.Mock
}

type LoyaltyBalancer_Expecter struct {
	mock *mock.Mock
}

func (_m *LoyaltyBalancer) EXPECT() *LoyaltyBalancer_Expecter {
	return &LoyaltyBalancer_Expecter{mock: &_m.Mock}
}

// LoyaltyAddWithdraw provides a mock function with given fields: ctx, userID, orderNum, withdraw
func (_m *LoyaltyBalancer) LoyaltyAddWithdraw(ctx context.Context, userID models.UserID, orderNum string, withdraw float64) error {
	ret := _m.Called(ctx, userID, orderNum, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for LoyaltyAddWithdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID, string, float64) error); ok {
		r0 = rf(ctx, userID, orderNum, withdraw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoyaltyBalancer_LoyaltyAddWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoyaltyAddWithdraw'
type LoyaltyBalancer_LoyaltyAddWithdraw_Call struct {
	*mock.Call
}

// LoyaltyAddWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID models.UserID
//   - orderNum string
//   - withdraw float64
func (_e *LoyaltyBalancer_Expecter) LoyaltyAddWithdraw(ctx interface{}, userID interface{}, orderNum interface{}, withdraw interface{}) *LoyaltyBalancer_LoyaltyAddWithdraw_Call {
	return &LoyaltyBalancer_LoyaltyAddWithdraw_Call{Call: _e.mock.On("LoyaltyAddWithdraw", ctx, userID, orderNum, withdraw)}
}

func (_c *LoyaltyBalancer_LoyaltyAddWithdraw_Call) Run(run func(ctx context.Context, userID models.UserID, orderNum string, withdraw float64)) *LoyaltyBalancer_LoyaltyAddWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserID), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyAddWithdraw_Call) Return(_a0 error) *LoyaltyBalancer_LoyaltyAddWithdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyAddWithdraw_Call) RunAndReturn(run func(context.Context, models.UserID, string, float64) error) *LoyaltyBalancer_LoyaltyAddWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// LoyaltyBalanceByUser provides a mock function with given fields: _a0, _a1
func (_m *LoyaltyBalancer) LoyaltyBalanceByUser(_a0 context.Context, _a1 models.UserID) (models.LoyaltyBalance, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for LoyaltyBalanceByUser")
	}

	var r0 models.LoyaltyBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) (models.LoyaltyBalance, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) models.LoyaltyBalance); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.LoyaltyBalance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoyaltyBalancer_LoyaltyBalanceByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoyaltyBalanceByUser'
type LoyaltyBalancer_LoyaltyBalanceByUser_Call struct {
	*mock.Call
}

// LoyaltyBalanceByUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.UserID
func (_e *LoyaltyBalancer_Expecter) LoyaltyBalanceByUser(_a0 interface{}, _a1 interface{}) *LoyaltyBalancer_LoyaltyBalanceByUser_Call {
	return &LoyaltyBalancer_LoyaltyBalanceByUser_Call{Call: _e.mock.On("LoyaltyBalanceByUser", _a0, _a1)}
}

func (_c *LoyaltyBalancer_LoyaltyBalanceByUser_Call) Run(run func(_a0 context.Context, _a1 models.UserID)) *LoyaltyBalancer_LoyaltyBalanceByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserID))
	})
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyBalanceByUser_Call) Return(_a0 models.LoyaltyBalance, _a1 error) *LoyaltyBalancer_LoyaltyBalanceByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyBalanceByUser_Call) RunAndReturn(run func(context.Context, models.UserID) (models.LoyaltyBalance, error)) *LoyaltyBalancer_LoyaltyBalanceByUser_Call {
	_c.Call.Return(run)
	return _c
}

// LoyaltyHistoryByUser provides a mock function with given fields: _a0, _a1
func (_m *LoyaltyBalancer) LoyaltyHistoryByUser(_a0 context.Context, _a1 models.UserID) ([]models.LoyaltyHistory, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for LoyaltyHistoryByUser")
	}

	var r0 []models.LoyaltyHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) ([]models.LoyaltyHistory, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) []models.LoyaltyHistory); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LoyaltyHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoyaltyBalancer_LoyaltyHistoryByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoyaltyHistoryByUser'
type LoyaltyBalancer_LoyaltyHistoryByUser_Call struct {
	*mock.Call
}

// LoyaltyHistoryByUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.UserID
func (_e *LoyaltyBalancer_Expecter) LoyaltyHistoryByUser(_a0 interface{}, _a1 interface{}) *LoyaltyBalancer_LoyaltyHistoryByUser_Call {
	return &LoyaltyBalancer_LoyaltyHistoryByUser_Call{Call: _e.mock.On("LoyaltyHistoryByUser", _a0, _a1)}
}

func (_c *LoyaltyBalancer_LoyaltyHistoryByUser_Call) Run(run func(_a0 context.Context, _a1 models.UserID)) *LoyaltyBalancer_LoyaltyHistoryByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserID))
	})
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyHistoryByUser_Call) Return(_a0 []models.LoyaltyHistory, _a1 error) *LoyaltyBalancer_LoyaltyHistoryByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoyaltyBalancer_LoyaltyHistoryByUser_Call) RunAndReturn(run func(context.Context, models.UserID) ([]models.LoyaltyHistory, error)) *LoyaltyBalancer_LoyaltyHistoryByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoyaltyBalancer creates a new instance of LoyaltyBalancer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoyaltyBalancer(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoyaltyBalancer {
	mock := &LoyaltyBalancer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
