// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	models "github.com/fishus/go-advanced-gophermart/pkg/models"

	storage "github.com/fishus/go-advanced-gophermart/internal/storage"
)

// Orderer is an autogenerated mock type for the Orderer type
type Orderer struct {
	mock.Mock
}

type Orderer_Expecter struct {
	mock *mock.Mock
}

func (_m *Orderer) EXPECT() *Orderer_Expecter {
	return &Orderer_Expecter{mock: &_m.Mock}
}

// OrderAdd provides a mock function with given fields: _a0, _a1
func (_m *Orderer) OrderAdd(_a0 context.Context, _a1 models.Order) (models.OrderID, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for OrderAdd")
	}

	var r0 models.OrderID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) (models.OrderID, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) models.OrderID); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.OrderID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Order) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_OrderAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderAdd'
type Orderer_OrderAdd_Call struct {
	*mock.Call
}

// OrderAdd is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Order
func (_e *Orderer_Expecter) OrderAdd(_a0 interface{}, _a1 interface{}) *Orderer_OrderAdd_Call {
	return &Orderer_OrderAdd_Call{Call: _e.mock.On("OrderAdd", _a0, _a1)}
}

func (_c *Orderer_OrderAdd_Call) Run(run func(_a0 context.Context, _a1 models.Order)) *Orderer_OrderAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *Orderer_OrderAdd_Call) Return(_a0 models.OrderID, _a1 error) *Orderer_OrderAdd_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_OrderAdd_Call) RunAndReturn(run func(context.Context, models.Order) (models.OrderID, error)) *Orderer_OrderAdd_Call {
	_c.Call.Return(run)
	return _c
}

// OrderAddAccrual provides a mock function with given fields: ctx, orderID, accrual
func (_m *Orderer) OrderAddAccrual(ctx context.Context, orderID models.OrderID, accrual decimal.Decimal) error {
	ret := _m.Called(ctx, orderID, accrual)

	if len(ret) == 0 {
		panic("no return value specified for OrderAddAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID, decimal.Decimal) error); ok {
		r0 = rf(ctx, orderID, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orderer_OrderAddAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderAddAccrual'
type Orderer_OrderAddAccrual_Call struct {
	*mock.Call
}

// OrderAddAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID models.OrderID
//   - accrual decimal.Decimal
func (_e *Orderer_Expecter) OrderAddAccrual(ctx interface{}, orderID interface{}, accrual interface{}) *Orderer_OrderAddAccrual_Call {
	return &Orderer_OrderAddAccrual_Call{Call: _e.mock.On("OrderAddAccrual", ctx, orderID, accrual)}
}

func (_c *Orderer_OrderAddAccrual_Call) Run(run func(ctx context.Context, orderID models.OrderID, accrual decimal.Decimal)) *Orderer_OrderAddAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *Orderer_OrderAddAccrual_Call) Return(_a0 error) *Orderer_OrderAddAccrual_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orderer_OrderAddAccrual_Call) RunAndReturn(run func(context.Context, models.OrderID, decimal.Decimal) error) *Orderer_OrderAddAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// OrderByFilter provides a mock function with given fields: _a0, _a1
func (_m *Orderer) OrderByFilter(_a0 context.Context, _a1 ...storage.OrderFilter) (models.Order, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrderByFilter")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...storage.OrderFilter) (models.Order, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...storage.OrderFilter) models.Order); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...storage.OrderFilter) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_OrderByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderByFilter'
type Orderer_OrderByFilter_Call struct {
	*mock.Call
}

// OrderByFilter is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...storage.OrderFilter
func (_e *Orderer_Expecter) OrderByFilter(_a0 interface{}, _a1 ...interface{}) *Orderer_OrderByFilter_Call {
	return &Orderer_OrderByFilter_Call{Call: _e.mock.On("OrderByFilter",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *Orderer_OrderByFilter_Call) Run(run func(_a0 context.Context, _a1 ...storage.OrderFilter)) *Orderer_OrderByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.OrderFilter, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(storage.OrderFilter)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Orderer_OrderByFilter_Call) Return(_a0 models.Order, _a1 error) *Orderer_OrderByFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_OrderByFilter_Call) RunAndReturn(run func(context.Context, ...storage.OrderFilter) (models.Order, error)) *Orderer_OrderByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// OrderByID provides a mock function with given fields: _a0, _a1
func (_m *Orderer) OrderByID(_a0 context.Context, _a1 models.OrderID) (models.Order, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for OrderByID")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) (models.Order, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) models.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_OrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderByID'
type Orderer_OrderByID_Call struct {
	*mock.Call
}

// OrderByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.OrderID
func (_e *Orderer_Expecter) OrderByID(_a0 interface{}, _a1 interface{}) *Orderer_OrderByID_Call {
	return &Orderer_OrderByID_Call{Call: _e.mock.On("OrderByID", _a0, _a1)}
}

func (_c *Orderer_OrderByID_Call) Run(run func(_a0 context.Context, _a1 models.OrderID)) *Orderer_OrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID))
	})
	return _c
}

func (_c *Orderer_OrderByID_Call) Return(_a0 models.Order, _a1 error) *Orderer_OrderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_OrderByID_Call) RunAndReturn(run func(context.Context, models.OrderID) (models.Order, error)) *Orderer_OrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderUpdateStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *Orderer) OrderUpdateStatus(_a0 context.Context, _a1 models.OrderID, _a2 models.OrderStatus) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for OrderUpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID, models.OrderStatus) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orderer_OrderUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderUpdateStatus'
type Orderer_OrderUpdateStatus_Call struct {
	*mock.Call
}

// OrderUpdateStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.OrderID
//   - _a2 models.OrderStatus
func (_e *Orderer_Expecter) OrderUpdateStatus(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Orderer_OrderUpdateStatus_Call {
	return &Orderer_OrderUpdateStatus_Call{Call: _e.mock.On("OrderUpdateStatus", _a0, _a1, _a2)}
}

func (_c *Orderer_OrderUpdateStatus_Call) Run(run func(_a0 context.Context, _a1 models.OrderID, _a2 models.OrderStatus)) *Orderer_OrderUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID), args[2].(models.OrderStatus))
	})
	return _c
}

func (_c *Orderer_OrderUpdateStatus_Call) Return(_a0 error) *Orderer_OrderUpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orderer_OrderUpdateStatus_Call) RunAndReturn(run func(context.Context, models.OrderID, models.OrderStatus) error) *Orderer_OrderUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersByFilter provides a mock function with given fields: ctx, limit, filters
func (_m *Orderer) OrdersByFilter(ctx context.Context, limit int, filters ...storage.OrderFilter) ([]models.Order, error) {
	_va := make([]interface{}, len(filters))
	for _i := range filters {
		_va[_i] = filters[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrdersByFilter")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, ...storage.OrderFilter) ([]models.Order, error)); ok {
		return rf(ctx, limit, filters...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, ...storage.OrderFilter) []models.Order); ok {
		r0 = rf(ctx, limit, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, ...storage.OrderFilter) error); ok {
		r1 = rf(ctx, limit, filters...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_OrdersByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersByFilter'
type Orderer_OrdersByFilter_Call struct {
	*mock.Call
}

// OrdersByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - filters ...storage.OrderFilter
func (_e *Orderer_Expecter) OrdersByFilter(ctx interface{}, limit interface{}, filters ...interface{}) *Orderer_OrdersByFilter_Call {
	return &Orderer_OrdersByFilter_Call{Call: _e.mock.On("OrdersByFilter",
		append([]interface{}{ctx, limit}, filters...)...)}
}

func (_c *Orderer_OrdersByFilter_Call) Run(run func(ctx context.Context, limit int, filters ...storage.OrderFilter)) *Orderer_OrdersByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.OrderFilter, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(storage.OrderFilter)
			}
		}
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *Orderer_OrdersByFilter_Call) Return(_a0 []models.Order, _a1 error) *Orderer_OrdersByFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_OrdersByFilter_Call) RunAndReturn(run func(context.Context, int, ...storage.OrderFilter) ([]models.Order, error)) *Orderer_OrdersByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderer creates a new instance of Orderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Orderer {
	mock := &Orderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
