// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	models "github.com/fishus/go-advanced-gophermart/pkg/models"

	storage "github.com/fishus/go-advanced-gophermart/internal/storage"
)

// Orderer is an autogenerated mock type for the Orderer type
type Orderer struct {
	mock.Mock
}

type Orderer_Expecter struct {
	mock *mock.Mock
}

func (_m *Orderer) EXPECT() *Orderer_Expecter {
	return &Orderer_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *Orderer) Add(_a0 context.Context, _a1 models.Order) (models.OrderID, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 models.OrderID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) (models.OrderID, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) models.OrderID); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.OrderID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Order) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Orderer_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Order
func (_e *Orderer_Expecter) Add(_a0 interface{}, _a1 interface{}) *Orderer_Add_Call {
	return &Orderer_Add_Call{Call: _e.mock.On("Add", _a0, _a1)}
}

func (_c *Orderer_Add_Call) Run(run func(_a0 context.Context, _a1 models.Order)) *Orderer_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *Orderer_Add_Call) Return(_a0 models.OrderID, _a1 error) *Orderer_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_Add_Call) RunAndReturn(run func(context.Context, models.Order) (models.OrderID, error)) *Orderer_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddAccrual provides a mock function with given fields: ctx, orderID, accrual
func (_m *Orderer) AddAccrual(ctx context.Context, orderID models.OrderID, accrual decimal.Decimal) error {
	ret := _m.Called(ctx, orderID, accrual)

	if len(ret) == 0 {
		panic("no return value specified for AddAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID, decimal.Decimal) error); ok {
		r0 = rf(ctx, orderID, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orderer_AddAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAccrual'
type Orderer_AddAccrual_Call struct {
	*mock.Call
}

// AddAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID models.OrderID
//   - accrual decimal.Decimal
func (_e *Orderer_Expecter) AddAccrual(ctx interface{}, orderID interface{}, accrual interface{}) *Orderer_AddAccrual_Call {
	return &Orderer_AddAccrual_Call{Call: _e.mock.On("AddAccrual", ctx, orderID, accrual)}
}

func (_c *Orderer_AddAccrual_Call) Run(run func(ctx context.Context, orderID models.OrderID, accrual decimal.Decimal)) *Orderer_AddAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID), args[2].(decimal.Decimal))
	})
	return _c
}

func (_c *Orderer_AddAccrual_Call) Return(_a0 error) *Orderer_AddAccrual_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orderer_AddAccrual_Call) RunAndReturn(run func(context.Context, models.OrderID, decimal.Decimal) error) *Orderer_AddAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFilter provides a mock function with given fields: _a0, _a1
func (_m *Orderer) GetByFilter(_a0 context.Context, _a1 ...storage.OrderFilter) (models.Order, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilter")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...storage.OrderFilter) (models.Order, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...storage.OrderFilter) models.Order); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...storage.OrderFilter) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_GetByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFilter'
type Orderer_GetByFilter_Call struct {
	*mock.Call
}

// GetByFilter is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...storage.OrderFilter
func (_e *Orderer_Expecter) GetByFilter(_a0 interface{}, _a1 ...interface{}) *Orderer_GetByFilter_Call {
	return &Orderer_GetByFilter_Call{Call: _e.mock.On("GetByFilter",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *Orderer_GetByFilter_Call) Run(run func(_a0 context.Context, _a1 ...storage.OrderFilter)) *Orderer_GetByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.OrderFilter, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(storage.OrderFilter)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Orderer_GetByFilter_Call) Return(_a0 models.Order, _a1 error) *Orderer_GetByFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_GetByFilter_Call) RunAndReturn(run func(context.Context, ...storage.OrderFilter) (models.Order, error)) *Orderer_GetByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: _a0, _a1
func (_m *Orderer) GetByID(_a0 context.Context, _a1 models.OrderID) (models.Order, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) (models.Order, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID) models.Order); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Orderer_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.OrderID
func (_e *Orderer_Expecter) GetByID(_a0 interface{}, _a1 interface{}) *Orderer_GetByID_Call {
	return &Orderer_GetByID_Call{Call: _e.mock.On("GetByID", _a0, _a1)}
}

func (_c *Orderer_GetByID_Call) Run(run func(_a0 context.Context, _a1 models.OrderID)) *Orderer_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID))
	})
	return _c
}

func (_c *Orderer_GetByID_Call) Return(_a0 models.Order, _a1 error) *Orderer_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_GetByID_Call) RunAndReturn(run func(context.Context, models.OrderID) (models.Order, error)) *Orderer_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByFilter provides a mock function with given fields: ctx, limit, filters
func (_m *Orderer) ListByFilter(ctx context.Context, limit int, filters ...storage.OrderFilter) ([]models.Order, error) {
	_va := make([]interface{}, len(filters))
	for _i := range filters {
		_va[_i] = filters[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, limit)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListByFilter")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, ...storage.OrderFilter) ([]models.Order, error)); ok {
		return rf(ctx, limit, filters...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, ...storage.OrderFilter) []models.Order); ok {
		r0 = rf(ctx, limit, filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, ...storage.OrderFilter) error); ok {
		r1 = rf(ctx, limit, filters...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orderer_ListByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByFilter'
type Orderer_ListByFilter_Call struct {
	*mock.Call
}

// ListByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - filters ...storage.OrderFilter
func (_e *Orderer_Expecter) ListByFilter(ctx interface{}, limit interface{}, filters ...interface{}) *Orderer_ListByFilter_Call {
	return &Orderer_ListByFilter_Call{Call: _e.mock.On("ListByFilter",
		append([]interface{}{ctx, limit}, filters...)...)}
}

func (_c *Orderer_ListByFilter_Call) Run(run func(ctx context.Context, limit int, filters ...storage.OrderFilter)) *Orderer_ListByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]storage.OrderFilter, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(storage.OrderFilter)
			}
		}
		run(args[0].(context.Context), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *Orderer_ListByFilter_Call) Return(_a0 []models.Order, _a1 error) *Orderer_ListByFilter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orderer_ListByFilter_Call) RunAndReturn(run func(context.Context, int, ...storage.OrderFilter) ([]models.Order, error)) *Orderer_ListByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *Orderer) UpdateStatus(_a0 context.Context, _a1 models.OrderID, _a2 models.OrderStatus) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderID, models.OrderStatus) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orderer_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type Orderer_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.OrderID
//   - _a2 models.OrderStatus
func (_e *Orderer_Expecter) UpdateStatus(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Orderer_UpdateStatus_Call {
	return &Orderer_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", _a0, _a1, _a2)}
}

func (_c *Orderer_UpdateStatus_Call) Run(run func(_a0 context.Context, _a1 models.OrderID, _a2 models.OrderStatus)) *Orderer_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OrderID), args[2].(models.OrderStatus))
	})
	return _c
}

func (_c *Orderer_UpdateStatus_Call) Return(_a0 error) *Orderer_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orderer_UpdateStatus_Call) RunAndReturn(run func(context.Context, models.OrderID, models.OrderStatus) error) *Orderer_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderer creates a new instance of Orderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Orderer {
	mock := &Orderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
